### ISSUE TITLE
Real Estate Co-Owner Summary

### ISSUE THREAD

**Issue by maryjohnston** [18F/e-QIP-prototype#1192] opened 2018-11-19 21:23 UTC
Foreign Financial Interests Real Estate Co-Owner Summary. eApp asks 'Are there any additional co-owners for this foreign financial interests controlled on your behalf to report? This question is not on e-QIP. However, the question is answered yes on eApp. The details provided are for entry #2 under Foreign Financial Interests Real Estate- Co-owners.
#1015

**Comment by ryanhofdotgov** [comment] 2018-12-10 17:47
Resolved in October, duplicate of https://github.com/18F/e-QIP-prototype/issues/919

**Closed by ryanhofdotgov** 2018-12-10 17:47 UTC
Labels: NBIB
