### ISSUE TITLE
Can't validate test 7

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#1041] opened 2018-10-22 05:48 UTC
**What did you do?**

Temporarily turn off React logging, so browser doesn't hang "forever" and just a few minutes. Open up dev console. 

Load up test case #7. Sign-in, click on Review sub-page in first section. Let browser work for a few minutes, until it finally errors out in the console.

<img width="400" alt="screen shot 2018-10-21 at 10 18 52 pm" src="https://user-images.githubusercontent.com/37100189/47278841-d7ed8d80-d580-11e8-8eeb-ba21cecdf3f5.png">

**Additional Information**

Seems to be related to this line in #1018 which was merged recently:
```
const errors = element.querySelectorAll('.field .messages .message.error')
```

Reverting #1018 on my local sandbox resolved the issue. I don't think the problem is specific to the version of `test7.json` that I'm working from in https://github.com/18F/e-QIP-prototype/tree/test7-take2

**Comment by hursey013** [comment] 2018-10-29 13:51
Duplicate of https://github.com/18F/e-QIP-prototype/issues/1038

**Closed by hursey013** 2018-10-29 13:51 UTC
