### ISSUE TITLE
Getting `Failed prop type` error when clicking section heading in navigation menu

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#447] opened 2018-06-20 06:38 UTC
**What did you do?**

Sign-in, click yes to instructions, scroll to see "Review and submit" section heading in navigation menu, click "Review and submit" section heading.

**What did you expect to see?**

Section heading menu expands, listing sub-sections. Introduction section displayed as-is in the content area in right pane.

**What did you see instead?**

Content area in right pane from Introduction section cleared, with just save button showing ("Saved just now")

JavaScript console reporting:
```
warning.js:33 Warning: Failed prop type: Invalid prop `onClick` of type `string` 
supplied to `Link`, expected `function`.
    in Link (created by SectionLink)
    in SectionLink (created by Section)
    in span (created by Section)
    in div (created by Section)
    in Section (created by RequiresAuth)
    in RequiresAuth (created by Connect(RequiresAuth))
    in Connect(RequiresAuth) (created by Connect(Connect(RequiresAuth)))
    in Connect(Connect(RequiresAuth)) (created by Navigation)
    in div (created by Navigation)
    in div (created by ToggleItem)
    in Show (created by ToggleItem)
    in span (created by ToggleItem)
    in div (created by ToggleItem)
    in ToggleItem (created by Navigation)
    in nav (created by Navigation)
    in Navigation (created by RequiresAuth)
    in RequiresAuth (created by Connect(RequiresAuth))
    in Connect(RequiresAuth) (created by Connect(Connect(RequiresAuth)))
    in Connect(Connect(RequiresAuth)) (created by App)
    in div (created by Sticky)
    in div (created by Sticky)
    in div (created by Sticky)
    in Sticky (created by App)
    in div (created by App)
    in div (created by App)
    in main (created by App)
    in div (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by AppWithForm)
    in AppWithForm (created by Route)
    in Route
    in Switch
    in Main
    in Router
    in Provider
```

**Additional Information**
Chrome 67.0.3396.87 on macOS 10.12

**Comment by afeld** [comment] 2018-07-03 18:57
Duplicate of #401.

**Closed by afeld** 2018-07-03 18:57 UTC
Labels: bug, pilot
