### ISSUE TITLE
validation error across the three fields to make up a date is not working fully

### ISSUE THREAD

**Issue by bpdesigns** [18F/e-QIP-prototype#641] opened 2018-08-02 17:51 UTC
**What did you do?**

Entered a valid address, then edited the day and month fields to be incorrect

**What did you expect to see?**

All three fields (including the year) to show an error
**What did you see instead?**

only the day and month field had an error 
**Additional Information**
<img width="746" alt="screen shot 2018-08-02 at 1 48 21 pm" src="https://user-images.githubusercontent.com/15329140/43601369-fe1a6a4c-965a-11e8-85e6-5a07ae7ad4a3.png">

 - What browser and version are you using?
chrome
 - What operating system?
mac

**Comment by bpdesigns** [comment] 2018-08-02 18:04
Seems to be that the three fields are working independently.

**Comment by christopherhuii** [comment] 2018-10-12 19:12
@bpdesigns @ryanhofdotgov Struggling to reproduce this issue. Are there any other instructions to help me reproduce?

**Comment by hursey013** [comment] 2018-10-15 18:57
I can't seem to reproduce this either.

**Comment by gidjin** [comment] 2018-10-17 05:18
Seems like we should close this or kick it back to get more detailed steps to reproduce since I also seem to be unable to reproduce it.

**Closed** 2018-10-17 15:28 UTC
Labels: drop-in, medium, validation
