### ISSUE TITLE
Citizenship - accordion titles

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#167] opened 2018-05-23 23:04 UTC
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2825  

Foreign passport accordion titles are being truncated to 1 letter

![screen shot 2018-04-03 at 3 26 55 pm](https://user-images.githubusercontent.com/19935974/38271390-5c47bf0e-3754-11e8-8e65-eeefea21ca7b.jpg)
![screen shot 2018-04-03 at 3 27 02 pm](https://user-images.githubusercontent.com/19935974/38271392-5c5371c8-3754-11e8-86b2-31dea71a406c.jpg)

**Comment by line47** [comment] 2018-06-14 15:36
I'm not able to reproduce this bug... @afeld how about you?
![screen shot 2018-06-14 at 11 33 08 am](https://user-images.githubusercontent.com/1449852/41422377-ca78a5ec-6fc6-11e8-991b-f9913dfcfecf.png)

At small screen size the country text starts to get chopped 
![screen shot 2018-06-14 at 11 35 27 am](https://user-images.githubusercontent.com/1449852/41422529-1704f618-6fc7-11e8-8127-c5245ed63c3a.png)

**Comment by line47** [comment] 2018-06-14 16:40
Could not reproduce - Closing

**Closed by line47** 2018-06-14 16:40 UTC
Labels: bug, high
