### ISSUE TITLE
Left Nav button issues

### ISSUE THREAD

**Issue by bpdesigns** [18F/e-QIP-prototype#455] opened 2018-06-20 14:10 UTC
**What did you do?**

I clicked on a top level section button on the left nav such as "2 Your History" 

**What did you expect to see?**

I expected it to show me the Introduction page for the "Your History" section

**What did you see instead?**

a blank screen

 - What browser and version are you using?
Chrome
 - What operating system?
Mac

**Comment by ryanhofdotgov** [comment] 2018-06-20 18:54
This might be a duplicate of https://github.com/18F/e-QIP-prototype/issues/447

**Comment by bpdesigns** [comment] 2018-06-20 20:11
It sounds related and fixing one could fix the other.

**Comment by afeld** [comment] 2018-07-05 17:17
Correction: it should keep the current content rather than clearing it out.

**Closed** 2018-07-05 20:34 UTC
Labels: bug, pilot
