### ISSUE TITLE
Specify home or work in eApp PDF for contact information

### ISSUE THREAD

**Issue by maryjohnston** [18F/e-QIP-prototype#1200] opened 2018-11-19 21:44 UTC
Section: Contact Information - e-QIP archival shows email address as 'home', eApp does not specify 'home' or 'work' #1015

**Comment by ryanhofdotgov** [comment] 2018-11-19 22:40
This is a duplicate of an issue resolved back in September https://github.com/18F/e-QIP-prototype/issues/781

**Closed by ryanhofdotgov** 2018-11-19 22:40 UTC
Labels: NBIB
