### ISSUE TITLE
Foreign Financial Interests Real Estate Co-owner Summary question should read : Are there any additional co-owners for this foreign real estate? 

### ISSUE THREAD

**Issue by maryjohnston** [18F/e-QIP-prototype#1193] opened 2018-11-19 21:24 UTC
Section: Foreign Financial Interests Real Estate Co-owner Summary - eApp asks: Are ther any additional co-owners for this foreign financial interests controlled on your behalf to report? The questions should read: Are there any additional co-owners for this foreign real estate? 
#1015

**Comment by ryanhofdotgov** [comment] 2018-12-10 17:52
Resolved in October, duplicate of #919 and #1192

**Closed by ryanhofdotgov** 2018-12-10 17:52 UTC
Labels: NBIB
