### ISSUE TITLE
Section 22 - Police Record:  street address is displayed for the questions in eApp and not eQip

### ISSUE THREAD

**Issue by maryjohnston** [18F/e-QIP-prototype#1203] opened 2018-11-19 21:48 UTC
Section 22 - Police Record : 
 The street address is displayed for the questions "Provide the location where the offense occurred"  in eAPP. not in eQip.
#1015

**Comment by maryjohnston** [comment] 2018-11-19 21:57
e-QIP does not support this option, so remove from eApp, please.

**Comment by ryanhofdotgov** [comment] 2018-12-11 00:14
This was corrected in October, duplicate of https://github.com/18F/e-QIP-prototype/issues/755

**Closed by ryanhofdotgov** 2018-12-11 00:14 UTC
Labels: NBIB
