### ISSUE TITLE
Safari - section nav green dots

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#236] opened 2018-05-23 23:28 UTC
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2393  

- [ ] Section nav green dots are not showing on first pass, only when user goes back to completed section

![screen shot 2018-01-12 at 11 29 31 am](https://user-images.githubusercontent.com/19935974/34885036-9feeb436-f78c-11e7-847f-81dc11015cf3.jpg)
![screen shot 2018-01-12 at 11 29 38 am](https://user-images.githubusercontent.com/19935974/34885038-a0e0749c-f78c-11e7-81e4-48f4be922891.jpg)

**Comment by afeld** [comment] 2018-07-06 05:51
Duplicate of #179.

**Closed by afeld** 2018-07-06 05:51 UTC
Labels: Safari - cross browser
